[project]
name = "chunk_video_content"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "aiofiles",
    "azure-servicebus",
    "azure-storage-blob",
    "azure-identity",
    "python-dotenv",
    "pydantic-settings",
    "moviepy",
    "core",
]

[tool.uv.sources]
core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["chunk_video_content"]
