apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexfile-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexfile-api
  template:
    metadata:
      labels:
        app: indexfile-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: indexfile-container
        image: ACRNAME.azurecr.io/indexfileapi:0.0.1
        env:
        - name: SERVICE_BUS_FULLY_QUALIFIED_NAMESPACE
          value: "SERVICE_BUS_FULLY_QUALIFIED_NAMESPACE"
        - name: INDEX_FILE_QUEUE
          value: "INDEX_FILE_QUEUE"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: indexfile-api-service
  namespace: default
spec:
  selector:
    app: indexfile-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
