[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "index_file_api_tests"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pytest",
    "pytest-asyncio",
    "httpx",
    "fastapi",
    "core",
    "src",
]

[tool.uv.sources]
core = { path = "../../core" }
src = { workspace = true }

[tool.uv.workspace]
members = [
    "core",
    "src",
]

[tool.pytest.ini_options]
testpaths = ["."]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
pythonpath = [
    ".",
    "..",
]
log_cli = true
log_cli_level = "INFO"

[tool.hatch.build.targets.wheel]
packages = ["index_file_api"]